{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kafka-sendgrid-event-sink.serviceAccountName" . }}
  labels:
{{ include "kafka-sendgrid-event-sink.labels" . | indent 4 }}
{{- end -}}
